import javax.management.Query

plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'ktb'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// webMVC
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'
	// JPA
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	// mySQL Driver
	runtimeOnly 'com.mysql:mysql-connector-j'
	// logging: p6spy
	implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.12.0'
	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
	// BCrypt (spring-security-crypto만)
	implementation 'org.springframework.security:spring-security-crypto'
	// QueryDSL
	implementation 'com.querydsl:querydsl-jpa:5.1.0:jakarta'
	annotationProcessor "com.querydsl:querydsl-apt:${dependencyManagement.importedProperties['querydsl.version']}:jakarta"
	annotationProcessor "jakarta.annotation:jakarta.annotation-api"
	annotationProcessor "jakarta.persistence:jakarta.persistence-api"
	// Spring Security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	//-- 테스트
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	// validation
	implementation 'org.springframework.boot:spring-boot-starter-validation:2.7.4'
	// monitoring
	implementation 'org.springframework.boot:spring-boot-starter-actuator' // SpringBoot 애플리케이션의 정보를 다룰 수 있게 함
	implementation 'io.micrometer:micrometer-registry-prometheus' // Prometheus가 읽을 수 있는 metrics를 제공
}

tasks.named('test') {
	useJUnitPlatform()
}
clean {
	delete file('src/main/generated')
}
