server:
  port: 8080
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  datasource:
    hikari:
      maximum-pool-size: 40
      connection-timeout: 3000
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?serverTimezone=UTC
    username: ${USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
    properties:
      hibernate:
        format_sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE # json 직렬화, 역직렬화

logging:

jwt:
  secret: ${JWT_SECRET}
  expiration-time: ${EXPIRATION_TIME}

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  metrics:
    tags:
      application: talk2wall-be
    distribution:
      percentiles-histogram:
        http.server.requests: true
        hikaricp.connections.usage: true
        hikaricp.connections.acquire: true
      slo:
        http.server.requests: 50ms,100ms,200ms,500ms,1s,2s,5s
        hikaricp.connections.acquire: 100us,500us,1ms,5ms,10ms,50ms,100ms,500ms,3s
        hikaricp.connections.usage: 500us,1ms,5ms,10ms,50ms,100ms,500ms,1s
